Rename boolean selects
cobudget/cobudget pull request #921
Opened 2022-12-30 20:05 UTC by alinauroz

for https://github.com/cobudget/cobudget/issues/913

2023-01-10 15:00 UTC, gustavlrsn requested changes
Looks good, just some strings that need to be internationalized.

2023-01-10 15:00 UTC, gustavlrsn commented on ui/components/RoundSettings/Granting/index.tsx
> +            secondary={round.requireBucketApproval ? "Yes" : "No"}
Same here

2023-01-10 15:00 UTC, gustavlrsn commented on ui/components/About/index.tsx
> +              secondary={round.allowStretchGoals ? "Yes" : "No"}
Make these internationalized

2023-01-11 18:42 UTC, alinauroz commented on ui/components/RoundSettings/Granting/index.tsx
> +            secondary={round.allowStretchGoals ? "Yes" : "No"}
done

2023-01-11 18:42 UTC, alinauroz commented on ui/components/RoundSettings/Granting/index.tsx
> +            secondary={round.requireBucketApproval ? "Yes" : "No"}
done

2023-01-11 18:42 UTC, alinauroz commented on ui/components/About/index.tsx
> +              secondary={round.allowStretchGoals ? "Yes" : "No"}
done

2023-01-14 19:32 UTC, merged